export { default as IoSocketStatus } from '../..\\node_modules\\nuxt-socket-io\\lib\\components\\SocketStatus.js'
export { default as AccountsForm } from '../..\\components\\accounts\\form.vue'
export { default as AccountsList } from '../..\\components\\accounts\\list.vue'
export { default as CardsForm } from '../..\\components\\cards\\form.vue'
export { default as CardsList } from '../..\\components\\cards\\list.vue'
export { default as AuthForm } from '../..\\components\\auth\\authForm.vue'
export { default as Home } from '../..\\components\\home\\home.vue'
export { default as OffersDetail } from '../..\\components\\offers\\detail.vue'
export { default as OffersForm } from '../..\\components\\offers\\form.vue'
export { default as OffersList } from '../..\\components\\offers\\list.vue'
export { default as OffersOld } from '../..\\components\\offers\\old.vue'
export { default as OffersProforma } from '../..\\components\\offers\\proforma.vue'
export { default as OffersSample } from '../..\\components\\offers\\sample.vue'
export { default as PanelForm } from '../..\\components\\panel\\form.vue'
export { default as SharedLoading } from '../..\\components\\shared\\loading.vue'
export { default as SharedNavbar } from '../..\\components\\shared\\navbar.vue'
export { default as ShipmentForm } from '../..\\components\\shipment\\form.vue'
export { default as SupplierForm } from '../..\\components\\supplier\\form.vue'
export { default as SupplierList } from '../..\\components\\supplier\\list.vue'
export { default as TransportCompany } from '../..\\components\\transport\\company.vue'
export { default as TransportInput } from '../..\\components\\transport\\input.vue'
export { default as TransportList } from '../..\\components\\transport\\list.vue'
export { default as UploadDocform } from '../..\\components\\upload\\docform.vue'
export { default as UploadForm } from '../..\\components\\upload\\form.vue'
export { default as UploadIsfform } from '../..\\components\\upload\\isfform.vue'
export { default as UploadList } from '../..\\components\\upload\\list.vue'
export { default as UploadSupplierform } from '../..\\components\\upload\\supplierform.vue'
export { default as TodoForm } from '../..\\components\\todo\\form.vue'
export { default as TodoList } from '../..\\components\\todo\\list.vue'
export { default as ContainerFollowForm } from '../..\\components\\container\\follow\\form.vue'
export { default as ContainerFollowList } from '../..\\components\\container\\follow\\list.vue'
export { default as ContainerInputForm } from '../..\\components\\container\\input\\form.vue'
export { default as ContainerInputList } from '../..\\components\\container\\input\\list.vue'
export { default as OrdersFormsChat } from '../..\\components\\orders\\forms\\chat.vue'
export { default as OrdersFormsCheck } from '../..\\components\\orders\\forms\\check.vue'
export { default as OrdersFormsCost } from '../..\\components\\orders\\forms\\cost.vue'
export { default as OrdersFormsDetail } from '../..\\components\\orders\\forms\\detail.vue'
export { default as OrdersFormsDetail2 } from '../..\\components\\orders\\forms\\detail2.vue'
export { default as OrdersFormsDocument } from '../..\\components\\orders\\forms\\document.vue'
export { default as OrdersFormsOrder } from '../..\\components\\orders\\forms\\order.vue'
export { default as OrdersFormsOrder2 } from '../..\\components\\orders\\forms\\order2.vue'
export { default as OrdersFormsProforma } from '../..\\components\\orders\\forms\\proforma.vue'
export { default as OrdersFormsReminder } from '../..\\components\\orders\\forms\\reminder.vue'
export { default as OrdersFormsSupplier } from '../..\\components\\orders\\forms\\supplier.vue'
export { default as OrdersFormsWorkerman } from '../..\\components\\orders\\forms\\workerman.vue'
export { default as FinanceFormsAdvancepayment } from '../..\\components\\finance\\forms\\advancepayment.vue'
export { default as FinanceFormsPo } from '../..\\components\\finance\\forms\\po.vue'
export { default as PanelProjectForm } from '../..\\components\\panel\\project\\form.vue'
export { default as PanelProjectList } from '../..\\components\\panel\\project\\list.vue'
export { default as OrdersListsList } from '../..\\components\\orders\\lists\\list.vue'
export { default as OrdersListsList2 } from '../..\\components\\orders\\lists\\list2.vue'
export { default as OrdersListsShipped } from '../..\\components\\orders\\lists\\shipped.vue'
export { default as PanelUsaForm } from '../..\\components\\panel\\usa\\form.vue'
export { default as PanelUsaList } from '../..\\components\\panel\\usa\\list.vue'
export { default as PanelPublishedList } from '../..\\components\\panel\\published\\list.vue'
export { default as FinanceListsCollection } from '../..\\components\\finance\\lists\\collection.vue'
export { default as FinanceListsCustomer } from '../..\\components\\finance\\lists\\customer.vue'
export { default as FinanceListsList } from '../..\\components\\finance\\lists\\list.vue'
export { default as FinanceListsPaid } from '../..\\components\\finance\\lists\\paid.vue'
export { default as FinanceListsPo } from '../..\\components\\finance\\lists\\po.vue'
export { default as PanelUsersForm } from '../..\\components\\panel\\users\\form.vue'
export { default as PanelUsersList } from '../..\\components\\panel\\users\\list.vue'
export { default as SampleFinanceForm } from '../..\\components\\sample\\finance\\form.vue'
export { default as SampleFinanceList } from '../..\\components\\sample\\finance\\list.vue'
export { default as SampleListForm } from '../..\\components\\sample\\list\\form.vue'
export { default as SampleList } from '../..\\components\\sample\\list\\list.vue'
export { default as SelectionCratesizeForm } from '../..\\components\\selection\\cratesize\\form.vue'
export { default as SelectionCratesizeList } from '../..\\components\\selection\\cratesize\\list.vue'
export { default as SelectionInputForm } from '../..\\components\\selection\\input\\form.vue'
export { default as SelectionInputList } from '../..\\components\\selection\\input\\list.vue'
export { default as Selection } from '../..\\components\\selection\\input\\selection.vue'
export { default as SalesBgpDetailForm } from '../..\\components\\sales\\bgp\\detailForm.vue'
export { default as SalesBgpDetailList } from '../..\\components\\sales\\bgp\\detailList.vue'
export { default as SalesBgpList } from '../..\\components\\sales\\bgp\\list.vue'
export { default as SalesBgpLists } from '../..\\components\\sales\\bgp\\lists.vue'
export { default as SalesBgpNewForm } from '../..\\components\\sales\\bgp\\newForm.vue'
export { default as SalesConsiderForm } from '../..\\components\\sales\\consider\\form.vue'
export { default as SalesConsiderList } from '../..\\components\\sales\\consider\\list.vue'
export { default as SalesFollowForm } from '../..\\components\\sales\\follow\\form.vue'
export { default as SalesFollowFormDetail } from '../..\\components\\sales\\follow\\formDetail.vue'
export { default as SalesFollowList } from '../..\\components\\sales\\follow\\list.vue'
export { default as SalesRepresentativeForm } from '../..\\components\\sales\\representative\\form.vue'
export { default as SalesRepresentativeList } from '../..\\components\\sales\\representative\\list.vue'
export { default as SalesTodoForm } from '../..\\components\\sales\\todo\\form.vue'
export { default as SalesTodo } from '../..\\components\\sales\\todo\\todo.vue'
export { default as SalesTodoTodos } from '../..\\components\\sales\\todo\\todos.vue'
export { default as CustomerBgpForm } from '../..\\components\\customer\\bgp\\form.vue'
export { default as CustomerBgpList } from '../..\\components\\customer\\bgp\\list.vue'
export { default as CustomerFairForm } from '../..\\components\\customer\\fair\\form.vue'
export { default as CustomerFairList } from '../..\\components\\customer\\fair\\list.vue'
export { default as CustomerMekmarForm } from '../..\\components\\customer\\mekmar\\form.vue'
export { default as CustomerMekmarList } from '../..\\components\\customer\\mekmar\\list.vue'
export { default as CustomerMekmarOrderlist } from '../..\\components\\customer\\mekmar\\orderlist.vue'
export { default as CustomerMekmarOrderproductlist } from '../..\\components\\customer\\mekmar\\orderproductlist.vue'
export { default as CustomerOfferForm } from '../..\\components\\customer\\offer\\form.vue'
export { default as CustomerOfferList } from '../..\\components\\customer\\offer\\list.vue'
export { default as CustomerSelectionForm } from '../..\\components\\customer\\selection\\form.vue'
export { default as CustomerSelectionList } from '../..\\components\\customer\\selection\\list.vue'
export { default as SharedCustomeInputCurrencyInput } from '../..\\components\\shared\\customeInput\\currencyInput.vue'
export { default as SharedCustomeInputCustominput } from '../..\\components\\shared\\customeInput\\custominput.vue'
export { default as TodoMainList } from '../..\\components\\todo\\main\\list.vue'
export { default as ReportsMekmarAyoForm } from '../..\\components\\reports\\mekmar\\ayo\\form.vue'
export { default as ReportsMekmarAyoList } from '../..\\components\\reports\\mekmar\\ayo\\list.vue'
export { default as ReportsMekmarGuCont } from '../..\\components\\reports\\mekmar\\gu\\cont.vue'
export { default as ReportsMekmarGuForwarding } from '../..\\components\\reports\\mekmar\\gu\\forwarding.vue'
export { default as ReportsMekmarGuLogs } from '../..\\components\\reports\\mekmar\\gu\\logs.vue'
export { default as ReportsMekmarGuMekus } from '../..\\components\\reports\\mekmar\\gu\\mekus.vue'
export { default as ReportsMekmarGuOrdererOperation } from '../..\\components\\reports\\mekmar\\gu\\ordererOperation.vue'
export { default as ReportsMekmarGuShippedOperation } from '../..\\components\\reports\\mekmar\\gu\\shippedOperation.vue'
export { default as ReportsMekmarForwardingList } from '../..\\components\\reports\\mekmar\\forwarding\\list.vue'
export { default as ReportsMekmarLoadingList } from '../..\\components\\reports\\mekmar\\loading\\list.vue'
export { default as ReportsMekmarMkByCustomer } from '../..\\components\\reports\\mekmar\\mk\\byCustomer.vue'
export { default as ReportsMekmarMkYearByMarketingForwarding } from '../..\\components\\reports\\mekmar\\mk\\yearByMarketingForwarding.vue'
export { default as ReportsMekmarMkYearByMarketingOrders } from '../..\\components\\reports\\mekmar\\mk\\yearByMarketingOrders.vue'
export { default as ReportsMekmarMkYearByPoOrders } from '../..\\components\\reports\\mekmar\\mk\\yearByPoOrders.vue'
export { default as ReportsMekmarSummaryDetail } from '../..\\components\\reports\\mekmar\\summary\\detail.vue'
export { default as ReportsMekmarSummaryList } from '../..\\components\\reports\\mekmar\\summary\\list.vue'
export { default as ReportsMekmerAtlantaList } from '../..\\components\\reports\\mekmer\\atlanta\\list.vue'
export { default as ReportsMekmerMineList } from '../..\\components\\reports\\mekmer\\mine\\list.vue'
export { default as ReportsMekmerProductionList } from '../..\\components\\reports\\mekmer\\production\\list.vue'
export { default as ReportsMekmerStockForm } from '../..\\components\\reports\\mekmer\\stock\\form.vue'
export { default as ReportsMekmerStockList } from '../..\\components\\reports\\mekmer\\stock\\list.vue'
export { default as ReportsMekmerFinanceFormsAdvancepayment } from '../..\\components\\reports\\mekmer\\finance\\forms\\advancepayment.vue'
export { default as ReportsMekmerFinanceFormsPo } from '../..\\components\\reports\\mekmer\\finance\\forms\\po.vue'
export { default as ReportsMekmerFinanceListsCollection } from '../..\\components\\reports\\mekmer\\finance\\lists\\collection.vue'
export { default as ReportsMekmerFinanceListsCustomer } from '../..\\components\\reports\\mekmer\\finance\\lists\\customer.vue'
export { default as ReportsMekmerFinanceListsList } from '../..\\components\\reports\\mekmer\\finance\\lists\\list.vue'
export { default as ReportsMekmerFinanceListsPaid } from '../..\\components\\reports\\mekmer\\finance\\lists\\paid.vue'
export { default as ReportsMekmerFinanceListsPo } from '../..\\components\\reports\\mekmer\\finance\\lists\\po.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
